### 1. 리스트 만들기

In [18]:
a = []
b = [1,2,3,4,5]
c = ['Life', 'is', 'too', 'shot']
person = ['james',17, 175.3, True]
e = list()

### 2. 리스트 인덱싱

In [20]:
a = [1,2,3]

In [22]:
a = [1, [1,2,3]]
print(a[0])
print(a[1])
print(a[1][0])

1
[1, 2, 3]
1


* 리스트 다중 중첩은 복잡해 질수도 있기 때문에 잘 사용하지는 않는다

In [23]:
matrix = [[0,1,2],
          [3,4,5],
          [4,5,6]]
print(matrix[0][0], matrix[0][1], matrix[0][2])
print(matrix[1][0], matrix[1][1], matrix[1][2])
print(matrix[2][0], matrix[2][1], matrix[2][2])

0 1 2
3 4 5
4 5 6


In [24]:
a = [1,2,3]
a[-1]

3

### 3. 리스트 슬라이싱

In [2]:
a =[1,2,3]
b =[4,5]
a.extend(b)
a

[1, 2, 3, 4, 5]

In [5]:
14 in a

False

In [7]:
a.count(1)

1

In [8]:
len(a)

5

In [5]:
a = (1,2,[1,2,3],3, "test")

In [7]:
a[2]

[1, 2, 3]

In [8]:
a =((1,2),(3,4))

In [9]:
a[0][0]

1

In [10]:
a[0][:]

(1, 2)

In [11]:
t = tuple()

In [13]:
t[0]=1

TypeError: 'tuple' object does not support item assignment

In [18]:
t = tuple()
for item in [1,2,3,4,5]:
    t = t + (item,)

In [19]:
t

(1, 2, 3, 4, 5)

In [22]:
a =set([1,2,3,3,3,4,5,5])

In [23]:
a

{1, 2, 3, 4, 5}

In [24]:
fruits = ['apple', 'kiwi', 'banana', 'blueberry']

for i, fruit in  enumerate(fruits):
    print(i, fruit)

0 apple
1 kiwi
2 banana
3 blueberry


In [25]:
a = {1,2,3}

In [27]:
2 in a

True

In [28]:
type(a)

set

In [38]:
list1 = [1,1,1,1]
list2 = [1,1,1,1]
data = [1,2,3,4,5]

In [40]:
data*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [31]:
list1+list2

[1, 1, 1, 1, 1, 1, 1, 1]

In [32]:
[x+y for x, y in zip(list1,list2)]

[2, 2, 2, 2]

In [42]:
import numpy as np
x = np.array(list1)
y = np.array(list2)
x*2

array([2, 2, 2, 2])

In [43]:
x

array([1, 1, 1, 1])

In [45]:
data=np.array(data)

In [46]:
data

array([1, 2, 3, 4, 5])

In [48]:
res = data == 1

In [49]:
res

array([ True, False, False, False, False])

In [51]:
res[1]

False