In [3]:
import numpy as np

In [5]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
a = np.arange(15).reshape(1,3,5)

In [22]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [23]:
a.ndim

3

In [10]:
a[2][0]=29

In [11]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [29, 11, 12, 13, 14]])

In [13]:
a.ndim

2

In [15]:
a[1][0]=103

In [16]:
a

array([[  0,   1,   2,   3,   4],
       [103,   6,   7,   8,   9],
       [ 29,  11,  12,  13,  14]])

In [17]:
a.ndim

2

In [19]:
a.shape

(3, 5)

In [20]:
a.shape(1,3,5)

TypeError: 'tuple' object is not callable

In [ ]:
data=np.array([[1,2,3],[4,5,6]])

In [ ]:
data.ndim

In [ ]:
data.shape

In [ ]:
type(data)

In [ ]:
data

In [ ]:
data[0][1]

In [ ]:
data[0,1]

In [ ]:
data[:,1]

In [ ]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = a > 7


In [ ]:
a[idx]

In [ ]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = a % 2 == 0
a[idx]

In [ ]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

In [ ]:
x = np.array([1, 2, 3], dtype='u8') # 부호 없는 정수
x.dtype

In [ ]:
x[0]+x[1]

In [ ]:
e = np.ones((2,3,4), dtype ='i8')
e

In [ ]:
np.empty((4,3), dtype='i8')

In [ ]:
a = np.arange(12)

In [ ]:
a

In [ ]:
a.reshape(3,4)

In [ ]:
a = a.reshape(3,4)

In [ ]:
a

In [ ]:
a.flatten()

In [ ]:
a.ravel()

In [ ]:
a

In [ ]:
a=a.flatten()

In [ ]:
a

In [ ]:
a[:]

In [ ]:
a[:,np.newaxis]

In [ ]:
print(np.newaxis)

In [ ]:
x = np.array([1,2,3])
x[:, np.newaxis]

In [ ]:
x = np.array([1,2,3,4])
y = np.array([4,2,2,4])
x+y

In [ ]:
x==y

In [ ]:
np.all(x==y)

In [ ]:
x = np.array([1,2,3,4])
y = np.array([4,2,2,4])
z = np.array([1,2,3,4])

In [ ]:
np.all(x==z)

In [ ]:
np.exp(x)

In [ ]:
10**x

In [ ]:
x = np.array([[1,2,3],[4,5,6]]) # 2행 3열
y = np.array([[1,1,1]])# 1행 3열
x+y

In [28]:
data.ndim

2

In [29]:
data.shape

(2, 3)

In [30]:
type(data)

numpy.ndarray

In [31]:
data

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
data[0][1]

2

In [35]:
data[0,1]

2

In [36]:
data[:,1]

array([2, 5])

In [42]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = a > 7


In [43]:
a[idx]

array([8, 9])

In [44]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = a % 2 == 0
a[idx]

array([0, 2, 4, 6, 8])

In [45]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [77]:
x = np.array([1, 2, 3], dtype='u8') # 부호 없는 정수
x.dtype

dtype('uint64')

In [76]:
x[0]+x[1]

3.0

In [78]:
e = np.ones((2,3,4), dtype ='i8')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [177]:
np.empty((4,3), dtype='i8')

array([[      1731946818632,                  64,                   0],
       [                  0,        210453397504, 7305228051307258422],
       [3919316087756829026, 7306308866838704484, 7004849166784685369],
       [3703702952011641657, 7365695899431952948, 3991141679790831410]],
      dtype=int64)

In [179]:
a = np.arange(12)

In [180]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [182]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [184]:
a = a.reshape(3,4)

In [185]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [186]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [187]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [188]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [189]:
a=a.flatten()

In [190]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [191]:
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [192]:
a[:,np.newaxis]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [195]:
print(np.newaxis)

None


In [198]:
x = np.array([1,2,3])
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [199]:
x = np.array([1,2,3,4])
y = np.array([4,2,2,4])
x+y

array([5, 4, 5, 8])

In [200]:
x==y

array([False,  True, False,  True])

In [201]:
np.all(x==y)

False

In [202]:
x = np.array([1,2,3,4])
y = np.array([4,2,2,4])
z = np.array([1,2,3,4])

In [203]:
np.all(x==z)

True

In [205]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [207]:
10**x

array([   10,   100,  1000, 10000], dtype=int32)

In [208]:
x = np.array([[1,2,3],[4,5,6]]) # 2행 3열
y = np.array([[1,1,1]])# 1행 3열
x+y

array([[2, 3, 4],
       [5, 6, 7]])