In [3]:
import numpy as np

In [5]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
a = np.arange(15).reshape(1,3,5)

In [22]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [23]:
a.ndim

3

In [10]:
a[2][0]=29

In [11]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [29, 11, 12, 13, 14]])

In [13]:
a.ndim

2

In [15]:
a[1][0]=103

In [16]:
a

array([[  0,   1,   2,   3,   4],
       [103,   6,   7,   8,   9],
       [ 29,  11,  12,  13,  14]])

In [17]:
a.ndim

2

In [19]:
a.shape

(3, 5)

In [20]:
a.shape(1,3,5)

TypeError: 'tuple' object is not callable