In [3]:
import numpy as np

In [5]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
a = np.arange(15).reshape(1,3,5)

In [22]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [23]:
a.ndim

3

In [10]:
a[2][0]=29

In [11]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [29, 11, 12, 13, 14]])

In [13]:
a.ndim

2

In [15]:
a[1][0]=103

In [16]:
a

array([[  0,   1,   2,   3,   4],
       [103,   6,   7,   8,   9],
       [ 29,  11,  12,  13,  14]])

In [17]:
a.ndim

2

In [19]:
a.shape

(3, 5)

In [20]:
a.shape(1,3,5)

TypeError: 'tuple' object is not callable

In [26]:
data=np.array([[1,2,3],[4,5,6]])

In [28]:
data.ndim

2

In [29]:
data.shape

(2, 3)

In [30]:
type(data)

numpy.ndarray

In [31]:
data

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
data[0][1]

2

In [35]:
data[0,1]

2

In [36]:
data[:,1]

array([2, 5])

In [42]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = a > 7


In [43]:
a[idx]

array([8, 9])

In [44]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = a % 2 == 0
a[idx]

array([0, 2, 4, 6, 8])

In [45]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [77]:
x = np.array([1, 2, 3], dtype='u8') # 부호 없는 정수
x.dtype

dtype('uint64')

In [76]:
x[0]+x[1]

3.0

In [78]:
e = np.ones((2,3,4), dtype ='i8')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [177]:
np.empty((4,3), dtype='i8')

array([[      1731946818632,                  64,                   0],
       [                  0,        210453397504, 7305228051307258422],
       [3919316087756829026, 7306308866838704484, 7004849166784685369],
       [3703702952011641657, 7365695899431952948, 3991141679790831410]],
      dtype=int64)