In [3]:
import numpy as np
import pandas as pd

In [20]:
#브로드캐스팅 예제

In [27]:
#브로드캐스팅 예제 1
M=np.ones((2,3))
a=np.arange(3)

print(M) # (2,3)
print(a) # (3,) => (1,3) => (2,3)
M+a 

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]


array([[1., 2., 3.],
       [1., 2., 3.]])

In [28]:
#브로드캐스팅 예제2

In [32]:
#브로드캐스팅 예제 2
a = np.arange(3).reshape((3,1))
b = np.arange(3) 

a #(3,1) ==> (3,3) 
b #(3,) => (1,3)==>(3,3)
a+b # 

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [20]:
#아래의 10*3 배열을 브로드캐스팅을 이용하여 centering 하세요
#X.mean(0)은 첫번째 차원의 특성별 평균
X=np.random.random((10,3))

In [21]:
X.mean(1)

array([0.39893776, 0.51642337, 0.51042241, 0.52866055, 0.40430425,
       0.43457529, 0.33592249, 0.15139051, 0.47041861, 0.56755031])

In [15]:
X.mean(0)

array([0.56987315, 0.43383959, 0.37547268])

In [17]:
X-X.mean(0)

array([[ 0.09917278, -0.21018463,  0.21109454],
       [-0.01015237,  0.00490998, -0.35318037],
       [ 0.19778408, -0.19711579, -0.21791059],
       [-0.23137823,  0.09052319,  0.33336001],
       [ 0.10369374,  0.18471546, -0.02030416],
       [-0.067057  , -0.30607001, -0.05895246],
       [ 0.05330008,  0.34344651, -0.24920264],
       [-0.39947204,  0.07976865,  0.35120746],
       [ 0.41564731, -0.11613369, -0.22439714],
       [-0.16153835,  0.12614034,  0.22828535]])

In [48]:
# 다음은 Seattle 2014년 강수량 데이터이다. 물음에 답하시오
csv_path = 'http://raw.githubusercontent.com/jakevdp/PythonDataScienceHandbook/master/notebooks/data/Seattle2014.csv'
rainfall = pd.read_csv(csv_path)['PRCP'].values
inches = rainfall / 254

#1. 비가오지 않은 날은 총 몇일인가?
np.sum(inches==0)

#2. 비가 온 날은 총 몇일인가?
np.sum(inches>0)

#3. 0.5 인치보다 크고, 1인치보다 작은 강수량은 총 몇일인가?
np.sum((inches > 0.5) & (inches <1))

29

In [69]:
rainy = (inches > 0)

summer = ((np.arange(365) -172 < 90)) & ((np.arange(365) -172) > 0)

# 비가 온 날의 강수량 평균?
np.mean(inches[rainy])

# 여름 강수량의 평균은?
np.mean(inches[summer])

# 여름에 최대 강수량은?
np.max(inches[summer])

#여름이외의 계절에 비가 온날의 강수량 평균은?
np.mean(inches[~summer & rainy])